[package]
name = "Naomii"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
port_check = "0.3.0"
windows-sys = "0.59.0" 
crossterm = "0.28"
rand = "0.8"
clap = { version = "4", features = ["derive"] }
